package com.gplsadgroup.ui;

import com.gplsadgroup.model.Order;
import com.gplsadgroup.model.User;
import com.gplsadgroup.repository.OrderRepository;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ReportFrame extends JFrame {

    private final OrderRepository orderRepository;
    private final User currentUser;

    private JLabel lblTotalRevenue;
    private JLabel lblTotalOrders;
    private JLabel lblAverageOrder;
    private JTable salesHistoryTable;
    private DefaultTableModel tableModel;

    public ReportFrame(OrderRepository orderRepository, User currentUser) {
        this.orderRepository = orderRepository;
        this.currentUser = currentUser;

        setTitle("Junaie's Flower Shop - Sales Reports & Analytics");
        setSize(800, 550);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        initUI();
        generateSalesReport();
    }

    private void initUI() {
        setLayout(new BorderLayout(10, 10));

        // Header
        JPanel headerPanel = new JPanel(new GridLayout(2, 1));
        headerPanel.setBorder(BorderFactory.createEmptyBorder(10, 15, 5, 15));
        JLabel lblHeader = new JLabel("Executive Sales Report", SwingConstants.CENTER);
        lblHeader.setFont(new Font("Arial", Font.BOLD, 18));
        JLabel lblUser = new JLabel("Generated by: " + currentUser.getFullName() + " (" + currentUser.getRole() + ")", SwingConstants.CENTER);
        lblUser.setFont(new Font("Arial", Font.ITALIC, 12));
        headerPanel.add(lblHeader);
        headerPanel.add(lblUser);
        add(headerPanel, BorderLayout.NORTH);

        // Center Panel: Analytics Summary + Detailed Sales History
        JPanel centerPanel = new JPanel(new BorderLayout(10, 10));
        centerPanel.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));

        // Metrics Summary Cards
        JPanel metricsPanel = new JPanel(new GridLayout(1, 3, 15, 0));
        metricsPanel.setBorder(BorderFactory.createTitledBorder("Key Performance Indicators (KPIs)"));

        lblTotalRevenue = createMetricLabel("Total Revenue", "₱0.00", new Color(0, 128, 0));
        lblTotalOrders = createMetricLabel("Total Transactions", "0", Color.BLUE);
        lblAverageOrder = createMetricLabel("Avg. Order Value", "₱0.00", Color.DARK_GRAY);

        metricsPanel.add(lblTotalRevenue);
        metricsPanel.add(lblTotalOrders);
        metricsPanel.add(lblAverageOrder);

        centerPanel.add(metricsPanel, BorderLayout.NORTH);

        // Sales History Table
        String[] columns = {"Order ID", "Cashier / Staff", "Date & Time", "Type", "Status", "Total Amount"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        salesHistoryTable = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(salesHistoryTable);
        scrollPane.setBorder(BorderFactory.createTitledBorder("Transaction History"));
        centerPanel.add(scrollPane, BorderLayout.CENTER);

        add(centerPanel, BorderLayout.CENTER);

        // Bottom Actions
        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 15, 10));
        JButton btnRefresh = new JButton("Refresh Data");
        bottomPanel.add(btnRefresh);
        add(bottomPanel, BorderLayout.SOUTH);

        btnRefresh.addActionListener(e -> generateSalesReport());
    }

    private JLabel createMetricLabel(String title, String value, Color color) {
        JLabel label = new JLabel("<html><center><b>" + title + "</b><br><font size='5' color='" + 
                toHexString(color) + "'>" + value + "</font></center></html>", SwingConstants.CENTER);
        label.setBorder(BorderFactory.createEtchedBorder());
        return label;
    }

    private String toHexString(Color color) {
        return String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());
    }

    private void generateSalesReport() {
        try {
            tableModel.setRowCount(0);
            List<Order> orders = orderRepository.findAll();

            BigDecimal totalRevenue = BigDecimal.ZERO;
            int totalOrders = orders.size();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

            for (Order o : orders) {
                totalRevenue = totalRevenue.add(o.getTotalAmount());
                String cashierName = (o.getUser() != null) ? o.getUser().getFullName() : "Unknown";
                String dateStr = (o.getOrderDate() != null) ? o.getOrderDate().format(formatter) : "N/A";

                tableModel.addRow(new Object[]{
                        "#" + o.getOrderId(),
                        cashierName,
                        dateStr,
                        o.getOrderType(),
                        o.getOrderStatus(),
                        "₱" + o.getTotalAmount()
                });
            }

            BigDecimal avgOrder = totalOrders > 0 
                    ? totalRevenue.divide(new BigDecimal(totalOrders), 2, RoundingMode.HALF_UP) 
                    : BigDecimal.ZERO;

            lblTotalRevenue.setText("<html><center><b>Total Revenue</b><br><font size='5' color='#008000'>₱" + String.format("%.2f", totalRevenue) + "</font></center></html>");
            lblTotalOrders.setText("<html><center><b>Total Transactions</b><br><font size='5' color='#0000FF'>" + totalOrders + "</font></center></html>");
            lblAverageOrder.setText("<html><center><b>Avg. Order Value</b><br><font size='5' color='#404040'>₱" + String.format("%.2f", avgOrder) + "</font></center></html>");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error generating report: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}